using Toklong.Domain.Transactions;

namespace Toklong.Application.Transactions;

public sealed record TransactionView(
    Guid Id,
    string PublicToken,
    string SellerAccessToken,
    string? BuyerAccessToken,
    TransactionState State,
    string StateLabel,
    string SellerDisplayName,
    string SellerContact,
    FulfillmentType FulfillmentType,
    string ProductName,
    string Category,
    ConditionCode Condition,
    string Description,
    string KnownDefects,
    string PhotoUrl,
    long PriceSatang,
    long ShippingFeeSatang,
    long BuyerTotalSatang,
    string Currency,
    int ShipByDurationHours,
    string TermsVersion,
    DateTimeOffset SellerAcceptedAt,
    string? BuyerDisplayName,
    string? BuyerContact,
    string? DeliveryAddress,
    DateTimeOffset? BuyerAcceptedAt,
    string? ProductSnapshotHash,
    DateTimeOffset? ShipByAt,
    string PaymentProvider,
    string? PaymentReference,
    DateTimeOffset? PaymentConfirmedAt,
    string? CarrierCode,
    string? TrackingNumber,
    DateTimeOffset? TrackingSubmittedAt,
    string? DigitalDeliveryStatement,
    DateTimeOffset? DigitalDeliverySubmittedAt,
    DateTimeOffset? DeliveredAt,
    DateTimeOffset? DisputeWindowEndsAt,
    DateTimeOffset? BuyerConfirmedAt,
    DisputeReason? DisputeReason,
    string? DisputeStatement,
    DateTimeOffset? DisputeOpenedAt,
    string? PayoutReference,
    DateTimeOffset? PayoutConfirmedAt,
    IReadOnlyList<AuditView> AuditEvents)
{
    public static TransactionView From(SaleTransaction transaction) => new(
        transaction.Id,
        transaction.PublicToken,
        transaction.SellerAccessToken,
        transaction.BuyerAccessToken,
        transaction.State,
        ThaiStateLabel(transaction.State),
        transaction.SellerDisplayName,
        transaction.SellerContact,
        transaction.FulfillmentType,
        transaction.ProductName,
        transaction.Category,
        transaction.Condition,
        transaction.Description,
        transaction.KnownDefects,
        transaction.PhotoUrl,
        transaction.PriceSatang,
        transaction.ShippingFeeSatang,
        transaction.BuyerTotalSatang,
        transaction.Currency,
        transaction.ShipByDurationHours,
        transaction.TermsVersion,
        transaction.SellerAcceptedAt,
        transaction.BuyerDisplayName,
        transaction.BuyerContact,
        transaction.DeliveryAddress,
        transaction.BuyerAcceptedAt,
        transaction.ProductSnapshotHash,
        transaction.ShipByAt,
        transaction.PaymentProvider,
        transaction.PaymentReference,
        transaction.PaymentConfirmedAt,
        transaction.CarrierCode,
        transaction.TrackingNumber,
        transaction.TrackingSubmittedAt,
        transaction.DigitalDeliveryStatement,
        transaction.DigitalDeliverySubmittedAt,
        transaction.DeliveredAt,
        transaction.DisputeWindowEndsAt,
        transaction.BuyerConfirmedAt,
        transaction.DisputeReason,
        transaction.DisputeStatement,
        transaction.DisputeOpenedAt,
        transaction.PayoutReference,
        transaction.PayoutConfirmedAt,
        transaction.AuditEvents.OrderByDescending(x => x.CreatedAt)
            .Select(x => new AuditView(x.Name, x.FromState, x.ToState, x.ActorRole, x.CreatedAt))
            .ToList());

    private static string ThaiStateLabel(TransactionState state) => state switch
    {
        TransactionState.LinkActive => "รอผู้ซื้อชำระ",
        TransactionState.CheckoutStarted or TransactionState.PaymentPending => "กำลังตรวจสอบการชำระ",
        TransactionState.PaidAwaitingShipment => "ชำระแล้ว · ส่งสินค้าได้",
        TransactionState.PaidAwaitingDigitalDelivery => "ชำระแล้ว · ส่งมอบข้อมูลได้",
        TransactionState.DigitalDeliverySubmitted => "ผู้ขายแจ้งว่าส่งมอบแล้ว · รอผู้ซื้อยืนยัน",
        TransactionState.TrackingSubmitted => "รอขนส่งตรวจสอบ Tracking",
        TransactionState.TrackingUnverified => "Tracking ยังตรวจสอบไม่ได้",
        TransactionState.InTransit => "กำลังจัดส่ง",
        TransactionState.DeliveredDisputeWindow => "พัสดุถึงแล้ว · อยู่ในช่วงตรวจสินค้า",
        TransactionState.BuyerConfirmedReceipt => "ผู้ซื้อยืนยันรับสินค้าแล้ว",
        TransactionState.Disputed or TransactionState.ResolutionPending => "พักการจ่ายระหว่างตรวจสอบ",
        TransactionState.PayoutEligible => "พร้อมเริ่มจ่ายเงิน",
        TransactionState.PayoutPending => "กำลังดำเนินการโอนให้ผู้ขาย",
        TransactionState.PaidOut => "โอนเงินให้ผู้ขายแล้ว",
        TransactionState.ShipmentOverdue => "เลยกำหนดส่ง",
        TransactionState.RefundPending => "กำลังคืนเงิน",
        TransactionState.Refunded => "คืนเงินแล้ว",
        TransactionState.Expired => "ลิงก์หมดอายุ",
        TransactionState.Cancelled => "ยกเลิกแล้ว",
        _ => "ฉบับร่าง"
    };
}

public sealed record AuditView(
    string Name,
    TransactionState FromState,
    TransactionState ToState,
    ActorRole ActorRole,
    DateTimeOffset CreatedAt);
