// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Toklong.Infrastructure.Persistence;

#nullable disable

namespace Toklong.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ToklongDbContext))]
    [Migration("20260725161631_TransactionRetentionLifecycle")]
    partial class TransactionRetentionLifecycle
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Toklong.Domain.Authentication.MobileSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BuyerId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("LastRotatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("RefreshTokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("SellerId")
                        .HasColumnType("uuid");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("BuyerId");

                    b.HasIndex("RefreshTokenHash")
                        .IsUnique();

                    b.HasIndex("SellerId");

                    b.ToTable("mobile_sessions", (string)null);
                });

            modelBuilder.Entity("Toklong.Domain.Buyers.BuyerAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTimeOffset>("PhoneVerifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SavedAddressLine")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset?>("SavedAddressUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("SavedDistrictId")
                        .HasColumnType("integer");

                    b.Property<string>("SavedDistrictName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SavedPostalCode")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<int?>("SavedProvinceId")
                        .HasColumnType("integer");

                    b.Property<string>("SavedProvinceName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("SavedSubdistrictId")
                        .HasColumnType("integer");

                    b.Property<string>("SavedSubdistrictName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.ToTable("buyers", (string)null);
                });

            modelBuilder.Entity("Toklong.Domain.Notifications.NotificationOutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer");

                    b.Property<string>("Audience")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset>("AvailableAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LastAttemptAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ProviderReference")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("Recipient")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)");

                    b.Property<DateTimeOffset?>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Template")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<Guid>("TransactionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TransactionId");

                    b.HasIndex("SentAt", "AvailableAt");

                    b.ToTable("notification_outbox", (string)null);
                });

            modelBuilder.Entity("Toklong.Domain.Sellers.SellerAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTimeOffset>("PhoneVerifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.ToTable("sellers", (string)null);
                });

            modelBuilder.Entity("Toklong.Domain.Sellers.SellerPayoutAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<string>("BankCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<Guid>("SellerId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SellerId", "AccountNumber");

                    b.ToTable("seller_payout_accounts", (string)null);
                });

            modelBuilder.Entity("Toklong.Domain.Transactions.ActivationRiskEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("ReasonCode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("Id");

                    b.ToTable("activation_risk_events", (string)null);
                });

            modelBuilder.Entity("Toklong.Domain.Transactions.AgreementAcceptance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("AcceptedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ActorUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("AgreementCoreSnapshotHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("AuthenticationMethod")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TermsSnapshotHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("TermsVersion")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<Guid>("TransactionId")
                        .HasColumnType("uuid");

                    b.Property<string>("VerifiedPhoneNumber")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)");

                    b.HasKey("Id");

                    b.HasIndex("TransactionId", "IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("TransactionId", "Role")
                        .IsUnique();

                    b.ToTable("agreement_acceptances", (string)null);
                });

            modelBuilder.Entity("Toklong.Domain.Transactions.AuditEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActorId")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("ActorRole")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FromState")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("ToState")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<Guid>("TransactionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TransactionId", "IdempotencyKey")
                        .IsUnique();

                    b.ToTable("audit_events", (string)null);
                });

            modelBuilder.Entity("Toklong.Domain.Transactions.ExternalEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("EventId")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TransactionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TransactionId");

                    b.HasIndex("Provider", "EventId")
                        .IsUnique();

                    b.ToTable("external_events", (string)null);
                });

            modelBuilder.Entity("Toklong.Domain.Transactions.FinancialRetentionRecord", b =>
                {
                    b.Property<Guid>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<DateTimeOffset>("EvidenceRetentionExpiredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("FinancialRetentionExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PaymentProvider")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("PaymentReference")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PayoutProvider")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("PayoutReference")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<long>("PlatformFeeSatang")
                        .HasColumnType("bigint");

                    b.Property<long>("PriceSatang")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("PurgedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RefundReference")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<DateTimeOffset>("RetentionStartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("SellerExpectedNetSatang")
                        .HasColumnType("bigint");

                    b.Property<string>("TerminalState")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.HasKey("TransactionId");

                    b.HasIndex("FinancialRetentionExpiresAt");

                    b.ToTable("financial_retention_records", (string)null);
                });

            modelBuilder.Entity("Toklong.Domain.Transactions.RetentionFileDeletion", b =>
                {
                    b.Property<Guid>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FileReference")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset>("QueuedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("TransactionId");

                    b.HasIndex("QueuedAt");

                    b.ToTable("retention_file_deletions", (string)null);
                });

            modelBuilder.Entity("Toklong.Domain.Transactions.SaleTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ActivatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("AgreementCoreSnapshotCreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AgreementCoreSnapshotHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("AgreementCoreSnapshotJson")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("AgreementSnapshotCreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("AgreementSnapshotSealedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("BuyerAcceptedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("BuyerAccessToken")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset?>("BuyerConfirmedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("BuyerContact")
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)");

                    b.Property<string>("BuyerDisplayName")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<Guid?>("BuyerId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("BuyerPaymentDeadlineAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CarrierCode")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<DateTimeOffset?>("DeliveredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeliveryAddress")
                        .HasColumnType("text");

                    b.Property<string>("DeliveryEventId")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<DateTimeOffset?>("DeliveryEventReceivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeliveryPostalCode")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<string>("DeliveryProvinceName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DigitalDeliveryStatement")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset?>("DigitalDeliverySubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DigitalManualReviewReference")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<DateTimeOffset?>("DisputeOpenedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisputeReason")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("DisputeResolutionReference")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<DateTimeOffset?>("DisputeResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisputeStatement")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("DisputeWindowEndsAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DisputeWindowStartsAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExpirationReason")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("FeePolicyVersion")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTimeOffset?>("FirstCarrierScanAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FulfillmentType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTimeOffset?>("InTransitAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InitiatorRole")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("InspectionWindowDurationHours")
                        .HasColumnType("integer");

                    b.Property<string>("KnownDefects")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("LegalHoldPlacedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LegalHoldReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("LegalHoldReference")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<DateTimeOffset?>("PaymentConfirmedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PaymentProvider")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("PaymentReference")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PayoutAccountName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("PayoutAccountNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<string>("PayoutBankCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset?>("PayoutConfirmedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PayoutProvider")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("PayoutReference")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("PayoutReleaseReason")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("PhotoUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("PlatformFeeSatang")
                        .HasColumnType("bigint");

                    b.Property<long>("PriceSatang")
                        .HasColumnType("bigint");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)");

                    b.Property<string>("ProductSnapshotHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ProductSnapshotJson")
                        .HasColumnType("text");

                    b.Property<string>("PublicToken")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset?>("RefundConfirmedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RefundReference")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<DateTimeOffset?>("RefundRequestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("RetentionExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("RetentionStartsAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("SellerAcceptanceDeadlineAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("SellerAcceptedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SellerAccessToken")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("SellerContact")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)");

                    b.Property<string>("SellerDisplayName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<long>("SellerExpectedNetSatang")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("SellerId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ShipByAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ShipByDurationHours")
                        .HasColumnType("integer");

                    b.Property<int?>("SnapshotSchemaVersion")
                        .HasColumnType("integer");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("TermsSnapshotHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("TermsSnapshotJson")
                        .HasColumnType("text");

                    b.Property<string>("TermsVersion")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("TrackingNumber")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTimeOffset?>("TrackingSubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TrackingVerificationStatus")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("BuyerAccessToken")
                        .IsUnique();

                    b.HasIndex("BuyerId");

                    b.HasIndex("PaymentReference")
                        .IsUnique();

                    b.HasIndex("PublicToken")
                        .IsUnique();

                    b.HasIndex("SellerAccessToken")
                        .IsUnique();

                    b.HasIndex("SellerId");

                    b.HasIndex("RetentionExpiresAt", "LegalHoldPlacedAt");

                    b.ToTable("transactions", (string)null);
                });

            modelBuilder.Entity("Toklong.Domain.Notifications.NotificationOutboxMessage", b =>
                {
                    b.HasOne("Toklong.Domain.Transactions.SaleTransaction", null)
                        .WithMany("Notifications")
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Toklong.Domain.Sellers.SellerPayoutAccount", b =>
                {
                    b.HasOne("Toklong.Domain.Sellers.SellerAccount", null)
                        .WithMany("PayoutAccounts")
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Toklong.Domain.Transactions.AgreementAcceptance", b =>
                {
                    b.HasOne("Toklong.Domain.Transactions.SaleTransaction", null)
                        .WithMany("AgreementAcceptances")
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Toklong.Domain.Transactions.AuditEvent", b =>
                {
                    b.HasOne("Toklong.Domain.Transactions.SaleTransaction", null)
                        .WithMany("AuditEvents")
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Toklong.Domain.Transactions.ExternalEvent", b =>
                {
                    b.HasOne("Toklong.Domain.Transactions.SaleTransaction", null)
                        .WithMany("ExternalEvents")
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Toklong.Domain.Transactions.SaleTransaction", b =>
                {
                    b.HasOne("Toklong.Domain.Buyers.BuyerAccount", null)
                        .WithMany()
                        .HasForeignKey("BuyerId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Toklong.Domain.Sellers.SellerAccount", b =>
                {
                    b.Navigation("PayoutAccounts");
                });

            modelBuilder.Entity("Toklong.Domain.Transactions.SaleTransaction", b =>
                {
                    b.Navigation("AgreementAcceptances");

                    b.Navigation("AuditEvents");

                    b.Navigation("ExternalEvents");

                    b.Navigation("Notifications");
                });
#pragma warning restore 612, 618
        }
    }
}
